<?php
/**
 * Copyright © 2016 iFlair Web Technologies. All rights reserved.
 */


/** @var $this IFlair_EasyCacheCleaner_Block_Adminhtml_Page_Header */
?>
<div class="header-top">
    <a href="<?php echo $this->getHomeLink() ?>"><img src="<?php echo $this->getSkinUrl('images/logo.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Magento Logo')) ?>" class="logo"/></a>
    <div class="header-right">
        <p class="super">
            <?php echo $this->__("Logged in as %s", $this->escapeHtml($this->getUser()->getUsername())) ?><span class="separator">|</span><?php echo $this->formatDate(null, 'full') ?><span class="separator">|</span><a href="<?php echo $this->getLogoutLink() ?>" class="link-logout"><?php echo $this->__('Log Out') ?></a>
        </p>
        <p class="easycachecleaner_wrapper super">
            <a href="javascript:void(0)" title="<?php echo $this->__('Refresh Cache') ?>" onclick="window.removeCache();">
            <img src='<?php echo $this->getSkinUrl('easycachecleaner/images/flash.png');?>' alt="<?php echo $this->__('Refresh Cache') ?>">
            </a>
        </p>
        <script type="text/javascript">
                window.removeCache = function() {
                    
                var ajaxBlockUrl = '<?php echo $this->getUrl('easycachecleaner/adminhtml_cache/massRefresh', array('_current' => true)) ?>';
                new Ajax.Request(ajaxBlockUrl, {
                    parameters: {isAjax: 'true', form_key: FORM_KEY},
                    onSuccess: function(transport) {
                        
                        try {
                            if (transport.responseText.isJSON()) {
                                var response = transport.responseText.evalJSON()
                                if (response.error || response.success) {
                                    var html = '<ul class="messages"><li class="'+response.type+'-msg"><ul><li>' + response.message + '</li></ul></li></ul>';
                                    $('messages').update(html);
                                }
                                if(response.ajaxExpired && response.ajaxRedirect) {
                                    setLocation(response.ajaxRedirect);
                                }
                            }
                        }
                        catch (e) {
                            
                        }
                    }
                });
            }
            </script>
        <?php if ( Mage::getSingleton('admin/session')->isAllowed('admin/global_search') ): ?>
        <fieldset>
            <legend>Search</legend>
            <span id="global_search_indicator" class="autocomplete-indicator" style="display: none">
                <img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading...')) ?>" class="v-middle"/>
            </span>
            <?php $defSearch = $this->__('Global Record Search') ?>
            <input id="global_search" name="query" type="text" class="input-text" value="<?php if(!empty($query)): ?><?php echo $query ?><?php else: ?><?php echo Mage::helper('core')->quoteEscape($defSearch) ?><?php endif ?>" onfocus="if(this.value=='<?php echo Mage::helper('core')->quoteEscape($defSearch, true) ?>')this.value=''; " onblur="if(this.value=='')this.value='<?php echo $defSearch ?>';" />
            <div id="global_search_autocomplete" class="autocomplete"></div>
            <script type="text/javascript">
                new Ajax.Autocompleter(
                    'global_search',
                    'global_search_autocomplete',
                    '<?php echo $this->getUrl('adminhtml/index/globalSearch') ?>',
                    {
                        paramName:"query",
                        minChars:2,
                        indicator:"global_search_indicator",
                        updateElement:getSelectionId,
                        evalJSON:'force'
                    }
                );
                function getSelectionId(li) {
                    location.href = li.getAttribute('url');
                }
            </script>
        </fieldset>
        <?php endif; ?>
    </div>
</div>
